FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD serve -s dist -l tcp://0.0.0.0:$PORT
